import { Backend } from "./backend";

// Patch Backend prototype to satisfy the platform's backendInterface contract.
// _initializeAccessControlWithSecret is expected by useActor.ts but is not
// generated by bindgen since the Motoko backend manages its own auth.
if (!(Backend.prototype as any)._initializeAccessControlWithSecret) {
  (Backend.prototype as any)._initializeAccessControlWithSecret = async (
    _adminToken: string,
  ): Promise<void> => {
    // no-op: this app uses its own admin token system
  };
}
